name: production-deployment
on:
  push:
    branches: [ dev ]

jobs:
  build:
    if: "!contains(toJSON(github.event.head_commit.message), '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      
    - name: Set Node 14 Context
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install
    - name: Build Project
      run: npm run build
      env:
        CI: false
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEPLOYMENT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOYMENT }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOYMENT }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: './dist/'

    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOYMENT }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOYMENT }}
