FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./indexer.py" , "-m", "5", "search.json"]
# CMD [ "python", "./estest.py"]